export default {
  ALLUSERSPROFILE: 'C:\\ProgramData',
  APPCODE_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\appcode.vmoptions',
  APPDATA: 'C:\\Users\\Firebat\\AppData\\Roaming',
  BABEL_ENV: 'development',
  BASE_API: '/devApi',
  CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\LOCAL\\crashpad_14252_REOJUGJZNQDTLVKQ',
  CLION_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\clion.vmoptions',
  COLORTERM: 'truecolor',
  CommonProgramFiles: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
  COMPUTERNAME: 'WINDOWS-01QEEPD',
  ComSpec: 'C:\\windows\\system32\\cmd.exe',
  DATAGRIP_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\datagrip.vmoptions',
  DATASPELL_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\dataspell.vmoptions',
  DEVECOSTUDIO_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\devecostudio.vmoptions',
  DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
  GATEWAY_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\gateway.vmoptions',
  GIT_ASKPASS: 'c:\\Users\\Firebat\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh',
  GOLAND_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\goland.vmoptions',
  HOMEDRIVE: 'C:',
  HOMEPATH: '\\Users\\Firebat',
  IDEA_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\idea.vmoptions',
  INIT_CWD: 'D:\\gitSpace\\1-vue2-template',
  JETBRAINSCLIENT_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\jetbrainsclient.vmoptions',
  JETBRAINS_CLIENT_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\jetbrains_client.vmoptions',
  LANG: 'zh_CN.UTF-8',
  LOCALAPPDATA: 'C:\\Users\\Firebat\\AppData\\Local',
  LOGONSERVER: '\\\\WINDOWS-01QEEPD',
  NODE: 'D:\\node\\node.exe',
  NODE_ENV: 'development',
  npm_config_argv: '{"remain":[],"cooked":["run","serve"],"original":["serve"]}',
  npm_config_bin_links: 'true',
  npm_config_ignore_optional: '',
  npm_config_ignore_scripts: '',
  npm_config_init_license: 'MIT',
  npm_config_init_version: '1.0.0',
  npm_config_registry: 'https://registry.yarnpkg.com',
  npm_config_save_prefix: '^',
  npm_config_strict_ssl: 'true',
  npm_config_user_agent: 'yarn/1.22.18 npm/? node/v16.14.0 win32 x64',
  npm_config_version_commit_hooks: 'true',
  npm_config_version_git_message: 'v%s',
  npm_config_version_git_sign: '',
  npm_config_version_git_tag: 'true',
  npm_config_version_tag_prefix: 'v',
  npm_execpath: 'C:\\Users\\Firebat\\AppData\\Roaming\\npm\\node_modules\\yarn\\bin\\yarn.js',
  npm_lifecycle_event: 'serve',
  npm_lifecycle_script: 'vue-cli-service serve --open',
  npm_node_execpath: 'D:\\node\\node.exe',
  npm_package_browserslist_0: '> 1%',
  npm_package_browserslist_1: 'last 2 versions',
  npm_package_browserslist_2: 'not dead',
  npm_package_dependencies_axios: '^1.3.4',
  npm_package_dependencies_babel_eslint: '^10.1.0',
  npm_package_dependencies_babel_preset_es2015: '^6.24.1',
  npm_package_dependencies_core_js: '^3.8.3',
  npm_package_dependencies_dhtmlx_gantt: '^8.0.2',
  npm_package_dependencies_echarts: '^5.4.1',
  npm_package_dependencies_element_ui: '^2.15.13',
  npm_package_dependencies_moment: '^2.29.4',
  npm_package_dependencies_sass: '^1.59.3',
  npm_package_dependencies_sass_loader: '^13.2.0',
  npm_package_dependencies_uuid: '^9.0.0',
  npm_package_dependencies_vue: '^2.6.14',
  npm_package_dependencies_vuedraggable: '^2.24.3',
  npm_package_dependencies_vuex: '3.6.2',
  npm_package_dependencies_vue_canvas_nest: '^2.0.0',
  npm_package_dependencies_vue_router: '3.4.9',
  npm_package_devDependencies_eslint: '^7.32.0',
  npm_package_devDependencies_eslint_plugin_vue: '^9.9.0',
  npm_package_devDependencies_vue_template_compiler: '^2.6.14',
  npm_package_devDependencies__babel_core: '^7.12.16',
  npm_package_devDependencies__babel_eslint_parser: '^7.12.16',
  npm_package_devDependencies__vue_cli_plugin_babel: '~5.0.0',
  npm_package_devDependencies__vue_cli_plugin_eslint: '~5.0.0',
  npm_package_devDependencies__vue_cli_service: '~5.0.0',
  npm_package_eslintConfig_env_node: 'true',
  npm_package_eslintConfig_extends_0: 'plugin:vue/essential',
  npm_package_eslintConfig_extends_1: 'eslint:recommended',
  npm_package_eslintConfig_parser: 'babel-eslint',
  npm_package_eslintConfig_parserOptions_parser: '@babel/eslint-parser',
  npm_package_eslintConfig_root: 'true',
  npm_package_name: 'vue-template',
  npm_package_private: 'true',
  npm_package_readmeFilename: 'README.md',
  npm_package_scripts_build: 'vue-cli-service build',
  npm_package_scripts_lint: 'vue-cli-service lint',
  npm_package_scripts_serve: 'vue-cli-service serve --open',
  npm_package_version: '0.1.0',
  NUMBER_OF_PROCESSORS: '16',
  OneDrive: 'D:\\oneDriveDownload\\OneDrive',
  OneDriveConsumer: 'D:\\oneDriveDownload\\OneDrive',
  ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
  OS: 'Windows_NT',
  // Path: 'C:\\Users\\Firebat\\AppData\\Local\\Temp\\yarn--1687683360795-0.4432098724558333;D:\\gitSpace\\1-vue2-template\\node_modules\\.bin;C:\\Users\\Firebat\\AppData\\Local\\Yarn\\Data\\link\\node_modules\\.bin;C:\\Users\\Firebat\\AppData\\Local\\Yarn\\bin;D:\\libexec\\lib\\node_modules\\npm\\bin\\node-gyp-bin;D:\\lib\\node_modules\\npm\\bin\\node-gyp-bin;D:\\node\\node_modules\\npm\\bin\\node-gyp-bin;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;D:\\node\\;D:\\WXDevTools\\微 
  // 信web开发者工具\\dll; C: \\Pro; ram Files\\MySQL\\MySQL Server 8.0\\bin\\; C: \\Program Files\\dotnet\\; D: \\Git\\cmd; D: \\GitExtensions\\; C: \\Program Files\\MySQL\\MySQL Shell 8.0\\bin\\; C: \\Users\\Firebat\\AppData\\Local\\Microsoft\\WindowsApps;; C: \\Users\\Firebat\\AppData\\Local\\Programs\\Microsoft VS 
  // Code\\bin; C: \\Users\\Firebat\\AppData\\Roaming\\npm',
  PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.CPL',
  PHPSTORM_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\phpstorm.vmoptions',
  PROCESSOR_ARCHITECTURE: 'AMD64',
  PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 141 Stepping 1, GenuineIntel',
  PROCESSOR_LEVEL: '6',
  PROCESSOR_REVISION: '8d01',
  ProgramData: 'C:\\ProgramData',
  ProgramFiles: 'C:\\Program Files',
  'ProgramFiles(x86)': 'C:\\Program Files (x86)',
  ProgramW6432: 'C:\\Program Files',
  PROMPT: '$P$G',
  PSModulePath: 'C:\\Users\\Firebat\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
  PUBLIC: 'C:\\Users\\Public',
  PYCHARM_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\pycharm.vmoptions',
  RIDER_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\rider.vmoptions',
  RUBYMINE_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\rubymine.vmoptions',
  SESSIONNAME: 'Console',
  STUDIO_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\studio.vmoptions',
  SystemDrive: 'C:',
  SystemRoot: 'C:\\windows',
  TEMP: 'C:\\Users\\Firebat\\AppData\\Local\\Temp',
  TERM_PROGRAM: 'vscode',
  TERM_PROGRAM_VERSION: '1.79.2',
  TMP: 'C:\\Users\\Firebat\\AppData\\Local\\Temp',
  USERDOMAIN: 'WINDOWS-01QEEPD',
  USERDOMAIN_ROAMINGPROFILE: 'WINDOWS-01QEEPD',
  USERNAME: 'Firebat',
  USERPROFILE: 'C:\\Users\\Firebat',
  VSCODE_GIT_ASKPASS_EXTRA_ARGS: '--ms-enable-electron-run-as-node',
  VSCODE_GIT_ASKPASS_MAIN: 'c:\\Users\\Firebat\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js',
  VSCODE_GIT_ASKPASS_NODE: 'C:\\Users\\Firebat\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
  VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-b8cfedcf6e-sock',
  VSCODE_INJECTION: '1',
  VUE_APP_AAA: '2222',
  WEBIDE_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\webide.vmoptions',
  WEBSTORM_VM_OPTIONS: 'D:\\DataGrip 2022.2.5\\jihuo-tool\\vmoptions\\webstorm.vmoptions',
  windir: 'C:\\windows',
  YARN_WRAP_OUTPUT: 'false',
  ZES_ENABLE_SYSMAN: '1'
}